version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "3000-3002:3000"
    depends_on:
      - redis
    deploy:
      replicas: 3
    environment:
      - PORT=3000
      - WORKERS=3
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge
volumes:
  redis-data: