services:
  node-app:
    build: .
    ports:
      - "3000-3002:3000"
    depends_on:
      - redis
      - localstack
    deploy:
      replicas: 3
    environment:
      - PORT=3000
      - WORKERS=3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://localstack:4566
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,athena,glue
      - DEBUG=1
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
      - LAMBDA_EXECUTOR=docker
      - CLEAR_TMP_FOLDER=0
      - TMPDIR=/tmp/localstack/tmp
      - LS_LOG=trace
    volumes:
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  redis-data:
  localstack-data:
    driver: local